CREATE TABLE Users (
  id INT IDENTITY(1,1) PRIMARY KEY,
  username NVARCHAR(100) NOT NULL,
  email NVARCHAR(255) NOT NULL,
  password NVARCHAR(255) NOT NULL,
  status NVARCHAR(20) NOT NULL DEFAULT 'PENDING',
  created_at DATETIME DEFAULT GETDATE()
);
